
samples: "config/samples.tsv"
config: "config/config.yaml"
comparisons: "config/comparisons.yaml"

# options are 'bwa' 'hisat2' and 'bowtie2'
aligner: 'bwa'

experiment_name: '2022_proMortalityExperiment_ribozero_wout_transcriptome'

htseq:
  mapping_qual_threshold: 10 # default is 10

feature_types_to_keep: [
'CDS',
'rRNA',
'tRNA',
'internal_ref'
]

input: 
  genome_refs: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/input_data_ribozero_wout_transcriptome/genomes
  gff_refs: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/input_data_ribozero_wout_transcriptome/annotations
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/ribozero_wout_transcriptome_intermediates
results: /nfs/chisholmlab001/kve/2022_proMortalityExperiment/ribozero_wout_transcriptome_results